spring.application.name=poster-monolith

server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/poster}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:poster}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED:true}
spring.liquibase.change-log=${SPRING_LIQUIBASE_CHANGE_LOG:classpath:db/changelog/db.changelog-master.yaml}